- alias: Fill next_alarm helper
  id: "9"
  description: Fills the next_alarm helper with the next occurring alarm.
  trigger:
    - platform: state
      entity_id: sensor.ryan_s_phone_next_alarm
    - platform: state
      entity_id: sensor.isabelle_s_phone_next_alarm
  condition:
    - condition: template
      value_template: >
        {{ nextAlarm is not none }}
  action:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.next_alarm
      data:
        timestamp: "{{ nextAlarm - 1}}"
  variables:
    ryanTimestamp: "{{as_timestamp(states('sensor.ryan_s_phone_next_alarm'))}}"
    izzyTimestamp: "{{as_timestamp(states('sensor.isabelle_s_phone_next_alarm'))}}"
    nextAlarm: >
      {% if ryanTimestamp is not none and (izzyTimestamp is none or ryanTimestamp < izzyTimestamp) %}{{ryanTimestamp}}
      {% else %}{{izzyTimestamp}}
      {% endif %}
  mode: single
