- platform: bayesian
  prior: 0.33
  name: Working
  probability_threshold: 0.85
  observations:
    - entity_id: "switch.tasmota_plug_3"
      prob_given_true: 0.99
      prob_given_false: 0.01
      platform: "state"
      to_state: "on"
