# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

# System
# Example configuration.yaml entry
logger:
  default: info
recorder:
  db_url: !secret db_url
  purge_keep_days: 7
  commit_interval: 60
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
    event_types:
      - call_service

# Text to speech
tts:
  - platform: google_translate

# Networking
http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
wake_on_lan:

# Media
samsungtv_smart:
  - host: 192.168.88.223
    app_list: '{"Amazon Music": "S9nU6P0m8Q.APM", "Disney Plus": "3201901017640/MCmYXNxgcu.DisneyPlus", "Hulu": "LBUAQX1exg.Hulu", "Netflix": "3201907018807/org.tizen.netflix-app", "Prime Video": "3201512006785/org.tizen.ignition", "Spotify": "3201606009684"}'

# Custom Components
pyscript:
  allow_all_imports: true
  hass_is_global: true

# Config Separation
alert: !include entities/alerts.yaml
automation manual: !include_dir_merge_list automations/manual/
automation ui: !include automations/ui_automations.yaml
group: !include entities/groups.yaml
light: !include entities/light_groups.yaml
notify: !include entities/notify.yaml
script: !include entities/scripts.yaml
sensor: !include entities/sensors.yaml
switch: !include entities/switches.yaml
template: !include entities/template.yaml
