- id: '1635962666659'
  alias: Shelly Button 2
  description: ''
  use_blueprint:
    path: custom/shelly-button1.yaml
    input:
      button: 17de100b6532817be7490fdbfbf2008c
      button_single: []
      button_double: []
      button_triple: []
      button_long: []
- id: '1635965302617'
  alias: Shelly Button 2
  description: ''
  use_blueprint:
    path: custom/shelly-button1.yaml
    input:
      button: 17de100b6532817be7490fdbfbf2008c
      button_single:
      - service: ''
        data: {}
- id: '1637097220475'
  alias: Low Battery Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.shelly_button_1_battery
    below: '20'
  - platform: numeric_state
    entity_id: sensor.shelly_button_2_battery
    below: '20'
  - platform: numeric_state
    entity_id: sensor.shelly_button_3_battery
    below: '20'
  - platform: numeric_state
    entity_id: sensor.shelly_button_4_battery
    below: '20'
  condition: []
  action:
  - device_id: 873167ebc67f9b5e6051fc5aa7ea122c
    domain: mobile_app
    type: notify
    title: '{{ state_attr(trigger.entity_id, ''friendly_name'') }} Battery Low'
    message: Plug it in!
  mode: single
- id: '1637698835569'
  alias: Toggle AdGuard when Hulu is Used
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.tv
    attribute: source
  condition: []
  action:
  - service: 'switch.turn_{{ "off" if trigger.to_state.attributes.source == "Hulu"
      else "on" }}

      '
    target:
      entity_id: switch.adguard_protection
  mode: single
- id: '1638236862457'
  alias: Samba Backup Alerts
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.samba_backup
    to: FAILED
  condition: []
  action:
  - device_id: 053446998b2a4f942d38f944439ac97c
    domain: mobile_app
    type: notify
    message: The backup was unsuccessful!
    title: Backup Failed
  mode: single
- id: '1640750159161'
  alias: ESP WROVER Buttons
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.red_button
    to: 'on'
    id: 'off'
  - platform: state
    entity_id: binary_sensor.green_button
    to: 'on'
    id: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.office_lights
        data:
          kelvin: 3000
          brightness_pct: '{{ ((states(''sensor.potentiometer'') | float(0) - 0.08)
            / 3.08 * 100) | int(100) }}'
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.office_lights
        data: {}
    default: []
  mode: single
- id: '1640816868797'
  alias: Office Dimmer
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.potentiometer
  condition:
  - condition: state
    entity_id: light.office_lights
    state: 'on'
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ ((states("sensor.potentiometer") | float(0) - 0.08) / 3.08
        * 100) | int(100) }}'
      kelvin: 3000
    target:
      entity_id: light.office_lights
  mode: single
- id: '1640818112697'
  alias: Mario
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.red_button
    to: 'on'
    from: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.office_lights
    data:
      brightness_pct: 100
      effect: Random
      color_name: red
  - service: esphome.test_play_rtttl
    data:
      song_str: '"mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6"'
  - delay:
      hours: 0
      minutes: 0
      seconds: 23
      milliseconds: 0
  - service: light.turn_on
    target:
      entity_id: light.office_lights
    data:
      effect: None
  - service: light.turn_off
    target:
      entity_id: light.office_lights
    data:
      transition: 1
  mode: single
- id: '1642709240729'
  alias: Shelly Button 1
  description: ''
  use_blueprint:
    path: custom/shelly-button1.yaml
    input:
      button: 55083f97ef6fb5bfe974b4cf8dd55d2e
      button_single:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.tasmota_bulb_5
      button_long:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.living_room_lights
- id: '1645026968224'
  alias: Shelly Button 4
  description: Automation for the Shelly1 in the Office.
  use_blueprint:
    path: custom/shelly-button1.yaml
    input:
      button: 3d4df902588c590801393deb506339c0
      button_single:
      - service: light.toggle
        target:
          entity_id: light.office_lights
- id: '1667173601671'
  alias: Turn on Wax Melter
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.tasmota_plug_1
  mode: single
- id: '1667173652725'
  alias: Turn off Wax Melter
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.tasmota_plug_1
  mode: single
- id: '1667517560328'
  alias: Motion Detection Test
  description: ''
  trigger:
  - platform: event
    event_type: motioneye.motion_detected
    event_data:
      device_id: 044809d4c3becf873ac018270051ec09
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ as_timestamp(now()) | timestamp_local }}'
    target:
      entity_id: input_text.test
  mode: single
- id: '1667765683549'
  alias: Shelly Button 3
  description: ''
  use_blueprint:
    path: custom/shelly-button1.yaml
    input:
      button: 3f0037350663df8bf0cbefa8fc48b45c
      button_single:
      - service: 'light.{% if states(''light.bedroom_lights'') == ''on'' %}turn_off{%
          else %}turn_on{% endif %}

          '
        data: '{% if states(''light.bedroom_lights'') == ''off'' %}{ ''brightness_pct'':
          100 }{% else %}{}{% endif %}

          '
        target:
          entity_id: 'light.{% if states(''light.bedroom_lights'') == ''on'' %}bedroom_lights{%
            else %}tasmota_bulb_1{% endif %}

            '
      button_double:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.tasmota_bulb_1
          - light.tasmota_bulb_2
      button_triple:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.tasmota_bulb_1
          - light.tasmota_bulb_2
          - light.tasmota_bulb_3
      button_long:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: light.bedroom_lights
- id: '1668297469037'
  alias: Update Isabelle's Device Tracker
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.sm_g973u1_geocoded_location
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: sm_g973u1
      gps: '{{ state_attr(''sensor.sm_g973u1_geocoded_location'', ''location'') }}'
  mode: single
- id: '1668646014401'
  alias: Set "Isabelle's Thing Ended" Datetime Helper
  description: ''
  trigger:
  - platform: state
    entity_id:
    - calendar.isabelle_general
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ state_attr(''calendar.isabelle_general'', ''description'')
      | length > 0 }}

      '
  action:
  - service: input_datetime.set_datetime
    data:
      datetime: '{{ (as_timestamp(today_at(state_attr(''calendar.isabelle_general'',
        ''end_time'').split('' '')[1][:-3]))  + (range(-15,15) | random * 60)) | timestamp_custom(''%Y-%m-%d
        %H:%M:%S'') }}

        '
    target:
      entity_id: input_datetime.isabelles_thing_ended
  mode: single
- id: '1668646074575'
  alias: Notify Ryan When Isabelle Has a Thing
  description: ''
  trigger:
  - platform: time
    at: input_datetime.isabelles_thing_ended
  condition: []
  action:
  - service: notify.mobile_app_pixel_6_pro
    data:
      title: Isabelle Has a Thing!
      message: '"{{ state_attr(''calendar.isabelle_general'', ''description'') }}"
        in {{ state_attr(''calendar.isabelle_general'', ''message'') }} ending at
        {{ state_attr(''calendar.isabelle_general'', ''end_time'').split('' '')[1][:-3]
        }}

        '
  mode: single
- id: '1673418393921'
  alias: 'Turn on bedroom lights in the morning '
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: person.ryan
    state: home
  - condition: or
    conditions:
    - condition: time
      before: 07:30:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: time
      after: 07:30:00
      weekday:
      - sat
      - sun
  action:
  - repeat:
      for_each: '{{ state_attr(''light.bedroom_lights'', ''entity_id'') }}'
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 1
        target:
          entity_id: '{{ repeat.item }}'
      - service: light.turn_on
        data:
          transition: 300
          brightness_pct: 100
        target:
          entity_id: '{{ repeat.item }}'
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - if:
        - condition: state
          entity_id: light.bedroom_lights
          state: 'off'
        then:
        - stop: 'Stop: Lights are off'
  mode: single
